name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual

jobs:
  build:
    runs-on: windows-latest  # Menggunakan Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Mengambil kode dari repo

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Sesuaikan dengan versi Python yang digunakan

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt  # Pastikan file requirements.txt ada

      - name: Build Executable
        run: |
          pyinstaller --onefile --console streamlit_app.py  # Sesuaikan dengan file utama Anda

      - name: Upload Artifact (Executable)
        uses: actions/upload-artifact@v4  # Perbarui ke v4
        with:
          name: Windows-Executable
          path: dist/streamlit_app.exe  # File hasil build

